"""Step 6 — engine migration policy: only unscored tournaments may migrate;
scored/completed are immutable; the action is owner-gated and audit-logged."""
import logging

import pytest

from app.extensions import db as _db
from app.models import (
    Tournament, TournamentParticipant, User,
    SCORING_ENGINE_LEGACY, SCORING_ENGINE_REFERENCE,
)
from app.services.tournament_scoring.engine_migration import (
    migration_eligibility, migrate_to_reference, MigrationNotAllowed,
)


def _legacy_tournament(status='draft', n=8, courts=2):
    t = Tournament(name='L', format='americano', num_courts=courts,
                   status=status, scoring_mode='points',
                   scoring_engine_version=SCORING_ENGINE_LEGACY)
    _db.session.add(t)
    _db.session.flush()
    ps = []
    for i in range(n):
        p = TournamentParticipant(tournament_id=t.id, name=f'P{i}', seed=i + 1)
        _db.session.add(p)
        ps.append(p)
    _db.session.flush()
    return t, ps


def _generate_legacy_rounds(t):
    from app.routes.tournament import _generate_all_rounds
    _generate_all_rounds(t)
    _db.session.commit()


def test_draft_unscored_is_eligible_and_migrates(app, db, caplog):
    t, _ = _legacy_tournament(status='draft')
    _generate_legacy_rounds(t)
    eligible, code, _ = migration_eligibility(t)
    assert eligible and code == 'ELIGIBLE'

    with caplog.at_level(logging.INFO):
        summary = migrate_to_reference(t, actor_id=42)
    _db.session.commit()

    assert t.scoring_engine_version == SCORING_ENGINE_REFERENCE
    assert summary['from_version'] == SCORING_ENGINE_LEGACY
    assert summary['actor_id'] == 42
    # rounds regenerated by the REFERENCE rotation: 8p natural -> exactly 7
    assert t.total_rounds == 7
    # audit trail emitted
    assert any('ENGINE_MIGRATION' in r.message for r in caplog.records)


def test_playing_without_scores_is_eligible(app, db):
    t, _ = _legacy_tournament(status='playing')
    _generate_legacy_rounds(t)          # rounds exist, all pending
    eligible, code, _ = migration_eligibility(t)
    assert eligible, code


def test_any_completed_match_blocks_migration(app, db):
    t, _ = _legacy_tournament(status='playing')
    _generate_legacy_rounds(t)
    m = t.rounds.first().matches.first()
    m.sets = [[21, 15]]
    m.status = 'completed'
    _db.session.commit()

    eligible, code, _ = migration_eligibility(t)
    assert not eligible and code == 'HAS_SCORES'
    with pytest.raises(MigrationNotAllowed):
        migrate_to_reference(t)
    assert t.scoring_engine_version == SCORING_ENGINE_LEGACY  # unchanged


def test_completed_tournament_is_immutable(app, db):
    t, _ = _legacy_tournament(status='completed')
    eligible, code, _ = migration_eligibility(t)
    assert not eligible and code == 'COMPLETED_IMMUTABLE'
    with pytest.raises(MigrationNotAllowed):
        migrate_to_reference(t)


def test_already_reference_is_refused(app, db):
    t, _ = _legacy_tournament()
    t.scoring_engine_version = SCORING_ENGINE_REFERENCE
    _db.session.commit()
    eligible, code, _ = migration_eligibility(t)
    assert not eligible and code == 'ALREADY_REFERENCE'


# ── API endpoint: gating + flow ─────────────────────────────────────────────

def _user(email, role='member'):
    u = User(username=email.split('@')[0], email=email, phone='08' + email[:6],
             role=role, membership='member', membership_paid=True)
    u.set_password('rahasia123')
    _db.session.add(u)
    _db.session.commit()
    return u


def _token(client, email):
    return client.post('/api/v1/auth/login',
                       json={'email': email, 'password': 'rahasia123'}
                       ).get_json()['data']['access_token']


def test_api_migrate_owner_flow(app, db, client):
    owner = _user('own@t.com')
    t, _ = _legacy_tournament(status='draft')
    t.created_by = owner.id
    _generate_legacy_rounds(t)
    tok = _token(client, 'own@t.com')

    # dry-run eligibility first — tidy flow
    e = client.get(f'/api/v1/tournaments/{t.id}/engine/eligibility',
                   headers={'Authorization': f'Bearer {tok}'}).get_json()['data']
    assert e['eligible'] is True and e['current_version'] == SCORING_ENGINE_LEGACY

    r = client.post(f'/api/v1/tournaments/{t.id}/engine/migrate',
                    headers={'Authorization': f'Bearer {tok}'})
    assert r.status_code == 200
    assert r.get_json()['data']['to_version'] == SCORING_ENGINE_REFERENCE


def test_api_migrate_non_owner_403(app, db, client):
    owner = _user('own@t.com')
    _user('other@t.com')
    t, _ = _legacy_tournament(status='draft')
    t.created_by = owner.id
    _db.session.commit()
    tok = _token(client, 'other@t.com')
    r = client.post(f'/api/v1/tournaments/{t.id}/engine/migrate',
                    headers={'Authorization': f'Bearer {tok}'})
    assert r.status_code == 403


def test_api_migrate_scored_returns_409(app, db, client):
    owner = _user('own@t.com')
    t, _ = _legacy_tournament(status='playing')
    t.created_by = owner.id
    _generate_legacy_rounds(t)
    m = t.rounds.first().matches.first()
    m.sets = [[21, 15]]
    m.status = 'completed'
    _db.session.commit()
    tok = _token(client, 'own@t.com')
    r = client.post(f'/api/v1/tournaments/{t.id}/engine/migrate',
                    headers={'Authorization': f'Bearer {tok}'})
    assert r.status_code == 409
    assert r.get_json()['error']['code'] == 'HAS_SCORES'
